### PR TITLE
Add instances for the 'binary' Get monad

### PR DESCRIPTION
**Pull request by mvv**
The `binary` package is already a dependency (via `text`).

### CODE REVIEW

**Comment by mvv** [comment]
Had to limit the feature to GHC >=7.10 (actually it compiles also with 7.0) due to `doctest` depending on `ghc`, which depends on `bin-package-db`, which depends on an old (older than the patch needs) version of `binary`. Not sure what is the best course here.

**Comment by mvv** [comment]
I guess one approach would be to disable the doctests test suite on GHC <7.10 like I did [here](https://github.com/mvv/parsers/commit/cfb7db81ed65b7e8b85bf8c185ec5f172ef3e473). What do you think?

**Comment by ekmett** [comment]
I'm going to leave this pull request open until I can, in good conscience, put a hard floor at ghc 7.10.

I have no objection to adding the instance per se. binary is pretty standard, but this requires me to clip into my current support window.

**Comment by mvv** [comment]
With `doctest` dep gone, the patch now works on all supported GHC versions. @ekmett, please consider merging.

**Pull request merged**
