### PR TITLE
There are no doctests, let's make package build-type: Simple

### PR DESCRIPTION
**Pull request by phadej**
ATM:

```
Examples: 0  Tried: 0  Errors: 0  Failures: 0
```

Otherwise it would be great to add examples, but if `parsers` are `build-type: Simple`, I'd be able to use them in `Cabal` tests (one cannot have `build-type: Custom` packages there, yet). See https://github.com/haskell/cabal/pull/4788#issuecomment-343612291

### CODE REVIEW

**Comment by ekmett** [comment]
Seems like we never got around to adding them. Might as well simplify this until we do.

**Comment by RyanGlScott** [comment]
@phadej, should we cut a new `parsers` release with this change soon, since you mentioned a use case in `Cabal`'s test suite?

**Comment by phadej** [comment]
If you can, that would be great. But it's ok to release later, if you procrastinate because of GHC-8.4 or something else

**Comment by RyanGlScott** [comment]
I've uploaded [`parsers-0.12.8`](http://hackage.haskell.org/package/parsers-0.12.8) to Hackage with this change.

**Comment by phadej** [comment]
Thanks!

**Pull request merged**
